### ISSUE TITLE
Current issues with direct Nearby uploads

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1329]
**Summary:** 

I thought we should probably keep a list of issues we are experiencing with the directNearbyUploadsNew feature branch, so we don't miss anything out before releasing to production. Please feel free to edit this post to add issues or detail for issues.

**Steps to reproduce:** 

Build from `2.7.x-release` and test the Nearby feature

- [x] 1. Memory leaks PR #1390 
- [x] 2. Crash when loading map (by the time I finished typing this out, I had lost the logcat. Sorry. :/ Will post when I encounter it again).
- [x] 3. <s>Text wrap issues in bottom sheet (see SS below). I would recommend removing "Directions" text</s>
- [x] 4. Fix "?" description bug in map (see SS below). This has already been fixed in list, we just need to copy the fix over to map. I should be able to do it after I'm done with my category PR.
- [x] 5. <s> Crash on orientation change</s> crashes when list view is open and orinetation changed. PR: #1385 
- [x] 6.  Bug: if you click one of nearby markers and make information bottom sheet visible, then go to settings and change theme, app will crash when you re-start nearby activity. Log is at below comment PR #1391
- [x] 7. <s> Action bar is hidden</s>
- [x] 8. Fix current location point visibility when bottom sheet is expanded, and re-center button is clicked. PR: #1381
- [x] 9. Fix transparent view is top of menu bar - PR is ready waiting for review #1378

![screenshot_20180318-194400](https://user-images.githubusercontent.com/3611199/37564649-ece24dc0-2ae5-11e8-817d-974f7d32a16d.png)

**Comment by neslihanturan** [comment]
3. Crash on orientation change

Then we are done. Btw weird, I could upload as far as I remember.

**Comment by misaochan** [comment]
I think the crash was caused by re-loading the map after submitting the upload, since the line pointed to was a "IndexOutOfBounds" error at `LatLng[] boundaryCoordinates = {places.get(0).location,   // south`. But I have not been able to reproduce it.

**Comment by misaochan** [comment]
@neslihanturan I found a couple more issues. Sorry! :D

**Comment by neslihanturan** [comment]
@misaochan I will be looking at those issues today, can you write your new couple more issues too?

**Comment by misaochan** [comment]
I added them to the opening post yesterday already. Thanks! :)

**Comment by neslihanturan** [comment]
+1 Bug, if you click one of nearby markers and make information bottom sheet visible, then go to settings and change theme, app will crash when you re-start nearby activity. Editing first entry accordingly.

**Comment by wailbabou** [comment]
[ 6 ] onStateChanged  called with STATE_SETTLING then STATE_HIDDEN  after changing theme ( `recreate()` ) and going back to nearByActivity 

Surrounding this line `getView().requestFocus()`  with try catch fixed it , even if it's not good solution

**Comment by 97balakrishnan** [comment]
I think the list button can be made as a toggle to show list of nearby places on first click and hide them on second click

**Comment by 97balakrishnan** [comment]
```
 FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                           Process: fr.free.nrw.commons.debug, PID: 19653
                                                                           io.reactivex.exceptions.UndeliverableException: java.lang.IndexOutOfBoundsException
                                                                               at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                               at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:48)
                                                                               at io.reactivex.Observable.subscribe(Observable.java:10901)
                                                                               at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                               at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.IndexOutOfBoundsException
                                                                               at java.util.Collections$EmptyList.get(Collections.java:102)
                                                                               at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:57)
                                                                               at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$6$NearbyActivity(NearbyActivity.java:317)
                                                                               at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$6.call(Unknown Source)
                                                                               at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
                                                                               at io.reactivex.Observable.subscribe(Observable.java:10901) 
                                                                               at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
                                                                               at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
```

I still get this crash when orientation changes when the options on nearby list is enabled

**Comment by 97balakrishnan** [comment]
```
03-21 16:59:08.519 24135-24135/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: fr.free.nrw.commons.debug, PID: 24135
                                                                           io.reactivex.exceptions.OnErrorNotImplementedException
                                                                               at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                               at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                               at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                               at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                               at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                               at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                               at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                            Caused by: java.lang.IndexOutOfBoundsException
                                                                               at java.util.Collections$EmptyList.get(Collections.java:102)
                                                                               at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:57)
                                                                               at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$6$NearbyActivity(NearbyActivity.java:317)
                                                                               at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$6.call(Unknown Source)
                                                                               at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
                                                                               at io.reactivex.Observable.subscribe(Observable.java:10901)
                                                                               at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                               at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:818)

```

I get this crash when internet is  unavailable

**Comment by neslihanturan** [comment]
Thanks for your reports @97balakrishnan

**Comment by neslihanturan** [comment]
It is good to inform everyone interested to solve these bugs, please do not solve them before dNUnew branch is merged to master. @maskaravivek is working to rebase, after that we can send PRs related with these bugs.

**Comment by neslihanturan** [comment]
I am currently working on "internet unavailable crash", letting you know to prevent two persons working on the same issue.

**Comment by 97balakrishnan** [comment]
Ok I'll work on the text wrap issue after the branch is merged

**Comment by neslihanturan** [comment]
@97balakrishnan just setting singleLine=true on xml should work when it comes to text wrap problem. Or we can remove the text _when there is no room_ . So we expect to see text when it fits. 

Note: Merge is done, you can send your PR

**Comment by maskaravivek** [comment]
Update: dnuNew is now merged with master. Moreover, @Jatin0312's recenter changes are also merged.

**Comment by neslihanturan** [comment]
@97balakrishnan after you saw that I was working on the internet thing and said "ok" , why did you create a related PR? We are not racing, we are colobrating please consider the comments next time...

**Comment by 97balakrishnan** [comment]
ok sorry :-)

**Comment by misaochan** [comment]
Thanks so much for working on this, guys! :)

Just checking on our progress - which items have been solved? I guess 1, 3, 5 and 6 are done?

**Comment by misaochan** [comment]
The action bar is currently hidden for me in Nearby and there is no way to bring it back. Not sure when this happened?

**Comment by misaochan** [comment]
I still get the below crash occasionally when I change orientation in Nearby, or sometimes even if I go to another activity and then return (e.g. uploading, or wikipedia, etc). It doesn't happen reliably, though.

```
03-26 18:37:09.683: E/AndroidRuntime(2741): FATAL EXCEPTION: main
03-26 18:37:09.683: E/AndroidRuntime(2741): Process: fr.free.nrw.commons.debug, PID: 2741
03-26 18:37:09.683: E/AndroidRuntime(2741): io.reactivex.exceptions.OnErrorNotImplementedException: Index: 0
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at android.os.Handler.handleCallback(Handler.java:751)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at android.os.Looper.loop(Looper.java:154)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.lang.reflect.Method.invoke(Native Method)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
03-26 18:37:09.683: E/AndroidRuntime(2741): Caused by: java.lang.IndexOutOfBoundsException: Index: 0
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.util.Collections$EmptyList.get(Collections.java:3690)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:57)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$6$NearbyActivity(NearbyActivity.java:351)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$6.call(Unknown Source)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.Observable.subscribe(Observable.java:10901)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-26 18:37:09.683: E/AndroidRuntime(2741): 	at java.lang.Thread.run(Thread.java:762)

```

**Comment by neslihanturan** [comment]
I am not able to reproduce the error @misaochan :/ Besides I added one more issue on main list

**Comment by misaochan** [comment]
@neslihanturan I'll try to look into the crash in that case, you can focus on 8. :)

**Comment by neslihanturan** [comment]
I was about to propose myself for 8 too:)

**Comment by neslihanturan** [comment]
We are almost done, except one leak, leak A at #1368

**Comment by misaochan** [comment]
Wonderful, great job @neslihanturan . :) Release will be coming up shortly!

**Comment by 97balakrishnan** [comment]
```
03-31 20:14:38.343 9842-9842/fr.free.nrw.commons.debug E/LocationServiceManager: Security exception
                                                                                 java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
                                                                                     at android.os.Parcel.readException(Parcel.java:1620)
                                                                                     at android.os.Parcel.readException(Parcel.java:1573)
                                                                                     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:106)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:94)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity.onStart(NearbyActivity.java:259)
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1260)
                                                                                     at android.app.Activity.performStart(Activity.java:6276)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```


getting this exception on first time loading of nearby places after granting permission.
Nearby location doesnt load the first time due to this exception
Device Android 6.0.1
Version 2.7.0-debug master

**Comment by 97balakrishnan** [comment]
The directions symbol is overlapped by recenter button.


![alt link](https://preview.ibb.co/b7zUx7/Screenshot_20180331_210950.png)

**Comment by misaochan** [comment]
Interesting, the directions symbol was never meant to be there. What happens when you select one of the pins and expand the bottom sheet?

**Comment by 97balakrishnan** [comment]
It remains there even if i select the pin and expand. Note: I got the directions symbol only after i zoomed the map. It was not initially present.

**Comment by misaochan** [comment]
Thanks @97balakrishnan . Could you create an issue for the problems you are experiencing, please? It would make it easier to organize the discussion.

**Comment by misaochan** [comment]
Thanks! As the release has gone ahead, I will close this so we can have a fresh start on discussing existing issues at #1400
