### ISSUE TITLE
List of issues that need hotfixes for 2.7

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1400]
Please rebase and submit PRs for these issues to the `2.7.x-release` branch, so that they can be included in the next hotfix (2.7.1). 

Essential:

- [x] #1395 Directions symbol gets overlapped by recenter button. PR #1423  (wanderlustnyc)
- [x] #1393 "My Recent Uploads" empty, spinning forever (@maskaravivek )
- [x]  #1413 Security exception. Old PR #1421, new PR #1440  (misaochan)
- [x]  #1437 Button that opens Google Maps shows always only the coordinates of the first chosen mark (kamilya35231). PR #1446 , **needs to be cherry picked**.
- [x] #1441 Compass button hidden by bottom sheet
- [x] #1401 User is no longer prompted to send ACRA crash reports  PR #1411 (tanvidadu)
- [x] #1416 Illegal state exception. PR #1425  (neslihanturan)
- [x] #1418 Blank category shown when submitting direct upload from a Nearby item without Commons category. PR #1426  (misaochan)
- [x] #1420 Initial permission request during direct upload does not take user to gallery/camera. PR #1424 (misaochan)

Nice to have:

- [x] #1431 It would be nice to fix one leak too. PR #1432 
- [x] #1427 Two NPEs that are new in version 2.7 - might not be needed once #1393 solved
- [x] #1412 Crash (SQLiteReadOnlyDatabaseException) when opening another activity after notifications activity  (neslihanturan)
- [x] #1399 Place description getting overlapped with plus fab button Nearby Activity PR #1405 (Jatin 0312)
- [x] #1398 Deletion Button getting disabled after clicking on cancel button PR #1403
- [x] #1419 Values in media details view are empty sometimes

**Comment by neslihanturan** [comment]
I am starting to work on security exception.

**Comment by neslihanturan** [comment]
Just waiting for #1433 , then we are done for 2.7.1 :tada:

**Comment by neslihanturan** [comment]
Essentials are done:)

**Comment by misaochan** [comment]
#1412 does not seem to be reported often. #2171 needs to be tested to see if the problem still exists after the recent upload overhaul in 2.9 - the networking code would've changed significantly then.
