### ISSUE TITLE
Items needed for v2.8 release

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1478]
v2.7 was pushed to production today. Hooray! That also means that it's time to start planning v2.8. :)

Required:
- [x] Featured images #324 @maskaravivek PR at #1456 
- [x] Wikidata edits and logging #252 #923 
- [x] Nearby places tutorial #706  @neslihanturan PR at #1467 
- [x] Refactor ShareActivity #1091  @misaochan PR at #1552 
- [x] Failed uploads #1485 - PR at #1790 
- [x] Remove retrieval of current location upon image upload (and associated setting) entirely (see #1599 ) @misaochan PR at #1644 
- [x] #1599 - very simple fix 
- [x] #1601 @maskaravivek 
- [x] #1637 fix Wikidata edits @maskaravivek 
- [x] Update Mapbox version, see #1659 
- [x] Fix prefill bug #1779 PR at #1779 
- [x] Top 5 crashes on Play Store #1545 @maskaravivek and @neslihanturan 
- [x] Thoroughly re-test master, and merge master into 2.8-release if viable
- [x] Remove http logging at #1751  or restrict to prod build
- [x] Find out what caused issue with Wikidata edits at #1601 
- [x] Add author field to browse #1801,  otherwise hide feature till next hotfix 

2.8.1 hotfix:
- Find out why Nearby edits occasionally fail #1804

**Comment by misaochan** [comment]
Bumping this as 2.8 will be scheduled soon with the completion of P18 edits. :) I think that once the urgent bugs/crashes are fixed, we will be good to go, hopefully by the end of this week or early next week. I have moved various large and non-urgent tasks down since including them in 2.8 would delay the release of P18 edits.

**Comment by ujjwalagrawal17** [comment]
@misaochan when are we releasing the beta for version 2.8. It would be great if we could include browsing images feature too. Searching images feature is already ready (some improvements are needed). Also, recent searches feature will be merged soon. I think it would be ready by end of this week or early next week at max.

**Comment by misaochan** [comment]
@ujjwalagrawal17 Hmm. We plan on releasing the beta late this week or early next week, but generally the last 1-2 weeks before the beta is released are reserved for testing and fixing bugs. Where possible, we tend to avoid adding new features in that time frame, as they also need to be tested and any bugs fixed, which would take another week or so.

How about we include your complete project in 2.9?

**Comment by misaochan** [comment]
Added #1515 and #1581 , removed the other unnecessary items.

**Comment by misaochan** [comment]
@maskaravivek @neslihanturan I have created the `2.8-release` branch in preparation for the release, please submit all bugfixes listed in this issue to that branch, thanks! :)

**Comment by neslihanturan** [comment]
Thanks, I love those lists @misaochan . They are very structured before release.

**Comment by neslihanturan** [comment]
I was working on #1480, but couldn't figure out the reason. I found some similar errors from mapbox repos and reported on our issue page.

Now I switched to work on "Top 5 crashes on Play Store", to use out time more efficient.

**Comment by misaochan** [comment]
@neslihanturan If you are doing #1545 , best to coordinate with @maskaravivek so that you both aren't working on the same crashes. :)

**Comment by neslihanturan** [comment]
@maskaravivek can I work on #1545 - A?

**Comment by maskaravivek** [comment]
@neslihanturan Sure pick that up. Meanwhile I will submit a PR for B.

**Comment by misaochan** [comment]
An additional issue that I found while doing the final pre-release testing - isDirectUpload seems to always return true, e.g. see log `07-17 18:45:27.672 6243-6243/fr.free.nrw.commons.debug D/ShareActivity: This was initiated by a direct upload from Nearby`. This means that uploads via Gallery or Camera also have their titles and descs prefilled by the last Nearby selection, which shouldn't happen.

Not sure when this bug was introduced, but it would have been after the last release. Should be a fairly easy fix, I'll work on it ASAP.

**Comment by misaochan** [comment]
As an update, given that this release has been delayed for so long pending a failed uploads fix, we may decide to merge the entirety of master into 2.8-release if our tests of master turn out OK. Does anyone know of any "dealbreaker" issues in master that may prevent this?

**Comment by misaochan** [comment]
Master works well for me upon extensive testing with a real device. Merging it into 2.8-release. :)

**Comment by misaochan** [comment]
This is done! Thanks everyone who participated. :) I will create a new issue for hotfixes needed.
