### ISSUE TITLE
Hotfixes needed for v2.8

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1814]
2.8.1
- [x] Find out why Nearby uploads occasionally fail #1804 @neslihanturan 
- [x] Categories are not set #1809 

2.8.3
- [ ] Wikidata edits and 2FA errors fixed #1866 
- [x] #1876 fixed or quiz checker disabled
- [x] #1877 fixed if possible

**Comment by misaochan** [comment]
I released 2.8.1 with just the category bug fixed, since we haven't had any luck with reproducing the occasional upload failure. Fingers crossed it stays that way, lol.

**Comment by misaochan** [comment]
Updated for 2.8.3
