### ISSUE TITLE
Items needed for v2.9

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1830]
We will hopefully be able to push 2.8 to production next week, and then on to 2.9! Fingers crossed, anyway. :)

Items needed:
- [x] Main UI overhaul #725 @neslihanturan 
- [x] Fix swipe sensitivity in main UI @ashishkumar468 
- [x] Prevent overwrites #703 
- [x] Fix .jpeg bug #1825 and overwrite issue #228 . Check that .png files can be uploaded via Share.
- [x] Fix issues with "send logs" #1489 @maskaravivek (this was originally slated for 2.10, but we really need it for debugging purposes, so we will be pushing this up to 2.9. In exchange, upload tests, which were originally slated for an earlier date, will be pushed down to 2.10)
- [x] Fix high-incidence crash on Android 8.1 and above #1877 
- [x] Fix issue with date not being included in recent uploads #1854 @ashishkumar468 
- [x] Fix top crashes in v2.8.4 #1917 (Volunteers have picked this up, PRs ready for testing)
- [x] Fix crash in Achievements #1930 
- [x]  fix issue with queued uploads #1878 (should have been fixed in 2.8.5)
- [x] Multiple uploads #604  PR at #1968 

If possible:
- [x] Solve Nearby zoom issue #1987 @ashishkumar468 
- [ ] Fix failing Wikidata edits in 2.8.5 #1866 
- [ ] Solve some small mem leaks #1996

**Comment by misaochan** [comment]
Pushing failed Wikidata edits to the next release as we have not gotten any logs of failed edits from 2.8.6 (if I missed one, please let me know!).

We're almost there for v2.9! :)
