### ISSUE TITLE
Hotfixes needed for 2.9.1 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2031]
- [x] Memory leaks on MainActivity #1996 
- [x] Crash on bookmarking an item from Explore #2041
- [ ] After re-logging, notifications bell icon is empty #2014 @neslihanturan 
- [ ] App stuck at "receiving shared content" #2033 @ashishkumar468 / @maskaravivek 
- [x] 2.9.0: Unable to exit app after going to notifications activity #2044 @misaochan 
- [x] Blank Achievements activity for some users #2042
- [x] Multiple uploads: If one description is empty, all pictures in batch will have no desc #2032 @misaochan / @maskaravivek 
- [x] When logging in after Skip Login, the usual main activity does not load #2030 
- [x] Attempt to invoke virtual method 'an droid.content.res.Resources android.view.View.getResources()' on a null object reference #2045
- [ ] Nearby: My position does not move #2062 @neslihanturan 
- [ ] Upload failures after v2.8 #2013 @ashishkumar468

**Comment by misaochan** [comment]
Thank you to our wonderful volunteers who have helped us with some of these issues while we were rushing for the 2.10 feature deadline!  :) Now that 2.10 is almost ready, we have decided that we will most likely skip 2.9.1 entirely and roll all of these fixes into 2.10. There are many bugfixes in master that we want to take advantage of, plus the automated releases via master will be very useful. 

This does mean that Play Store production users will skip 2.9 entirely (as 2.9.0 has a few bugs that would not pass muster in production). However, given that we can output 2.10 in almost the same timeframe as 2.9.1, there would be minimal downside to this for them.

**Comment by misaochan** [comment]
I have copied the remaining bugfixes needed over to #2171
