### ISSUE TITLE
v2.10 beta release checklist

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2171]
Features:

- [x] #591 
- [x] #945 
- [x] #78 
- [x] #1556 

Bugfixes:

- [x] After re-logging, notifications bell icon is empty #2014 @neslihanturan PR is up #2173
- [x] App stuck at "receiving shared content" #2033 @maskaravivek 
- [x] Nearby: My position does not move #2062 
- [x] Upload failures after v2.8 #2013 (Possibly fixed, let's see what the response is)
- [x] Switch to new image library to solve #2286 
- [x] Fix date issue #1971

**Comment by misaochan** [comment]
Just updated this. It seems we have only one critical issue left, then we can start preparing to release 2.10! :)

**Comment by misaochan** [comment]
Aaaannndd.... we're ready to go! 2.10 beta out today tentatively. :)
