### ISSUE TITLE
Items needed for v2.11 release

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3024]
Please make sure bugfixes for all the below items are submitted to `2.11-release` branch, thanks!

- [x] Fix for bug introduced in #2937 ( #3038 ) - @maskaravivek 
- [x] #3027 
- [x] #3028 
- [x] #3029 (awaiting Vitaly's PR)
- [x] #3036
- [ ] #3030 if possible (included in Nearby refactor so might be postponed depending on timeline)

**Comment by ashishkumar468** [comment]
@misaochan We don't need to cherry-pick #3062 from master, the crash was because of some changes in master which are not there in 2.11. Can one of you guys @maskaravivek @neslihanturan please confirm ?

**Comment by neslihanturan** [comment]
You are right @ashishkumar468 if your refactor of contributions fragment is not in 2.11, then no need for #3062 too.

**Comment by misaochan** [comment]
@ashishkumar468 as you were the one who reported the bug, I trust you know where it was from (but next time follow the issue template and mention the app version! ;)). Thanks for the heads up, I have removed the item from the checklist. 

2.11 should be out soon, hooray!

**Comment by misaochan** [comment]
Update: Discovered a bug where default language is set to Afrikaans always, which is a blocker. Tentative release date is next Monday if we can fix the bug by then.

**Comment by misaochan** [comment]
Pushed from beta to production today.
