### ISSUE TITLE
Items required for v2.12 release

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3115]
- [x] #3026 Retrofit migration- fixbugs mentioned at https://github.com/commons-app/apps-android-commons/issues/3026#issuecomment-511732535 and https://github.com/commons-app/apps-android-commons/issues/3026#issuecomment-511812380 (pending date bug and overwrite bug) @ashishkumar468 
- [x] Logout https://github.com/commons-app/apps-android-commons/pull/3150#discussion_r331743965 fixed @ashishkumar468 
- [x] https://github.com/wikimedia/wikimedia-android-data-client/issues/21 solved for Wikidata edits @maskaravivek 
- [x] #1092 all items completed for backend overhaul 
- [x] #2969 Nearby refactor PR merged
- [x] #1450 Nearby filters completed @neslihanturan 
- [x] #3144 2FA logins fixed. Logs should also NOT contain user's password.
- [x] #3126 Fix wrong dates @misaochan 
- [x] Nearby movement update issue fixed
- [x] #3147 Author bug fixed @maskaravivek 
- [x] #3174 Nomination for deletion fixed
- [x] #3217

**Comment by misaochan** [comment]
Released to beta. :)
