### ISSUE TITLE
Items needed for v2.13

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3334]
**31 Mar:** 2.13-release branch is cut, all PRs targeting 2.13 should be rebased there or cherrypicked from master

Changes/enhancements:
- [x] #3304 and #3322 merged
- [x] Nearby filters changes: #3355 and #3235 
- [x] Handle zoom in media details view #3414
- [x] Switch to Room completed
- [x] Decide if we want to include #3505  (included)

Bugfixes:
- [x] #3236 solved
- [x] #3359 assigned @ashishkumar468 
- [x] #3333 assigned @neslihanturan 
- [x] #2911
- [x] #3464 almost done, requested some changes
- [x] #3391 assigned @neslihanturan 
- [x] #3575 flickering colors @ashishkumar468 
- [x] #3576 wrong autofill @maskaravivek 
- [x] Either test ALL dialogs as mentioned at https://github.com/commons-app/apps-android-commons/issues/3576#issuecomment-603277538 , or revert #3496 . If we choose to revert, then #3577 must be reversed as well.
- [x] #3466 Fix email logs
- [x] #3195 Fix ordering in contributions list - we should cherry-pick this PR
- [x] #3607 App crash on open (this will not happen for end users)
- [x] #3624 (to fix an erroneous format introduced in #3589 ). This also needs to be cherrypicked from master
- [x] #3179 Fix category search
- [x] Check that all major 2.12 crashes have been fixed or are not relevant anymore
- [x] #3627 tested and merged
- [x] #3639 unmarshalling exception - we thought this was fixed :(
- [x] #3720 
- [x] #3704 
- [ ] #3705 

New features:
**Edit:** These might be pushed to 2.14 in order to get 2.13 changes out first.
- [ ] #3222 SDC merged to master
- [ ] #1831 Fill media legend implemented
- [ ] #1499 Nearby bookmarks implemented
- [ ] #161 Modify categories/description implemented
- [ ] #746 Limited connection mode implemented

**Comment by maskaravivek** [comment]
@misaochan Having #1831 as part of the release is dependant on #3222.

**Comment by misaochan** [comment]
Update: @ashishkumar468 (our bug smasher) has been feeling unwell and is taking a week off, but he has gone through the dev console crashes and submitted #3627 - after that is merged, he recommends going ahead with the release and handling the minor crashes after.

Next week I will do the final release testing, and if everything checks out we can probably expect 2.13 by the end of the week.

**Comment by misaochan** [comment]
Neslihan and I both had to take leave this week as well - apologies to anyone whose ping I missed in the meantime. Will be back next week.

**Comment by misaochan** [comment]
v2.13 was just released on beta. It might take a while to get to users though, as the dev console says 

> Due to adjusted work schedules at this time, we are currently experiencing longer than usual review times
> Please expect review times of seven days or longer.

**Comment by sivaraam** [comment]
@misaochan Has 2.13 started reaching the users? On seeing your e-mail to Wikimedia-mobile, I thought 2.13 might've started reaching users but when I try to install the production variant via play store I get 2.12.3 instead of 2.13. 🤔

**Comment by misaochan** [comment]
Hi @sivaraam , it is released for beta testing at the moment. :) Should be in production in a couple weeks' time.
