### ISSUE TITLE
Items required for v3.0

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3765]
New features:
- [x] Nearby bookmarks
- [x] Structured data merged into master
- [x] #872 and #1870 completed
- [x] Legacy issues sorted out for structured data
- [x] #3757 Make upload steps (esp categories and depicts) more explicit
- [x] Chunked uploads and limited connection mode
- [x] New UI #3891 
- [x] #4017 add limited connection mode display in UI (PR is up at #4094 )

Bugfixes:
 - [x] #3762 Invisible pins on Nearby map are still targetable 
- [x] #3856 p18 edit issue
- [x] Look into master upload failures #3868
- [x] #3903 corrupted uploads fixed
- [x] #3920 log files fixed
- [x] #3940 merged to update target sdk
- [x] #3992 upload failures solved
- [x] #343 
- [x] #4012 
- [x] #4014 
- [x] #4015 
- [x] #4016 / #3684 (PR is up #4082 )
- [x] #4018
- [x] #4019 
- [x] #4020 (PR is up #4029)
- [x] #3981 (PR is up #4107)

**Comment by misaochan** [comment]
Released to beta. :)
