### ISSUE TITLE
Items required for v3.0.1

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4155]
- [x] #4141 SQL error fixed
- [x] UI improvements, pending @neslihanturan 's investigations (UI fixes cherrypicked)
- [x] #4147 Prefill desc with Wikidata item's label + description
- [x] #4157 Back button in Media Details view
- [x] #4173 ACRA crash report version name
- [x] #4156 Location not available
- [x] #4283 media details view crash

**Comment by misaochan** [comment]
Released to beta today.
