### ISSUE TITLE
Items required for v3.1

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4386]
New features:
- [ ] #545 Add support for campaigns

Bugfixes:
- [x] #4344 Duplicate uploads when uploading 10 pictures
- [ ] #3792 Fix SQLite error, again
- [ ] #4435 Room schema error - update DB version

**Comment by misaochan** [comment]
As discussed with @neslihanturan , we are trialling out the use of milestones for releases instead of issue lists, for better automation and deadline handling. https://github.com/commons-app/apps-android-commons/milestone/4
