### ISSUE TITLE
Blockers for 4.2.0 release

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5308]
Any blockers for 4.2.0? Feel free to add if I missed something.

Must fix:

- [x] #5323 prodRelease build error
- [x] https://github.com/commons-app/apps-android-commons/issues/5273 On a fresh install, the location permission request dialog opens as expected but the "Turn on location?" dialog does not open.
- [x] https://github.com/commons-app/apps-android-commons/issues/5303 Crash on lowest supported API 21. Maybe increment minSdk to 23?

Would be much better to fix, but not a blocker either:

- [x]  #5342
- [x] #5339
- [x] https://github.com/commons-app/apps-android-commons/issues/5305 Annoying UX
- [x] #5321
- [ ] https://github.com/commons-app/apps-android-commons/issues/5324
- [x] #5212

**Comment by nicolas-raoul** [comment]
@sivaraam I believe all blockers are fixed. How about pushing a release to our beta testers? :-)

**Comment by sivaraam** [comment]
There's a regression in Ritika's changes that's discussed in https://github.com/commons-app/apps-android-commons/issues/5273#issuecomment-1732990195

I think it would be nice to see the fix for that before the release? It's resulting in the in-app camera upload not opening when location is turned off.

**Comment by nicolas-raoul** [comment]
@sivaraam I think all blockers are fixed now, there are a few things that are not polished but nothing that justifies holding back the greatness of this new version from our users, I believe. :-)

**Comment by sivaraam** [comment]
Sure. Let me look into pushing a release over the weekend. 👍🏼

**Comment by sivaraam** [comment]
Reg. the release. I've created the tag [v4.2.0](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.0) and [included the release notes for the same](https://github.com/commons-app/apps-android-commons/blob/main/CHANGELOG.md#v420). Let me know in case I've missed to include anything in the release notes.

I'm facing some odd issues with building the release variant of the app. Somehow it seems like Proguard doesn't work with Java 11 all of a sudden (it says it only supports Java 10 max.). I'm unable to build the data-client when switching to Java 8. Not sure about the cause of this. @nicolas-raoul Feel free to push a beta release if you could do so. Otherwise, I'll look into the root-cause of this and push the beta soon.

Note: It's a bit sad that the CI still fails. It would be nice if we're able to figure out the reason behind the failure of the same. I suppose it is fine if we skip that for the beta release, at least. We should definitely get it back to shape for the production release.

**Comment by mnalis** [comment]
> Note: It's a bit sad that the CI still fails

- (ref: https://github.com/commons-app/apps-android-commons/issues/5245)

**Comment by sivaraam** [comment]
After crossing some hurdles with getting the production APK (as observed via conversations at #5323 ), pushed out the v4.2.0 beta release for review today. The changes are available in the [v4.2.0-beta](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.0-beta) tag which points at a commit from the v4.2.0-release branch. 

PS: I've deleted the previous v4.2.0 tag as it didn't contain code that was in releasable state.

**Comment by mnalis** [comment]
> PS: I've deleted the previous v4.2.0 tag as it didn't contain code that was in releasable state.

Great to see progress on long awaited release @sivaraam!

Though, I'd highly advise _**against reusing `v4.2.0` tag**_ at least (go with `v4.2.1` for actual working release). Becuase, git won't overwrite existing tags in other forks by default, same tag for different commits would also cause all kind of logistic problems trying to report bug or trace where exactly it happened, it might cause issues with autobuilders (e.g. will f-droid build catch the new release if tag didn't change?) etc. And nothing good would come out from reusing `v4.2.0` tag.

(I probably wouldn't have even removed the tag, just marked it as buggy -- as realistically, every `.0` release is kind-of expected to be at least somewhat buggy anyway :smiley_cat: ; no need to stress about it. But it is also OK if tag is removed, just let's not reintroduce such "burnt" tag later)

**Comment by sivaraam** [comment]
That's a good point @mnalis! I'll avoid deleting the tag in future and make sure push out actual prod using a different tag 👍🏼 

PS: I'll try and push out that v4.2.0 tag as it used to be for reference purposes, if possible.

**Comment by sivaraam** [comment]
For the note, I've pushed out the deleted v4.2.0 again and released it as a [broken version](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.0). The [v4.2.0-beta](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.0-beta) has the actual working code.

**Comment by nicolas-raoul** [comment]
We now have 166 users on the 4.2.0 beta, and still zero ANR/crash :-)
![Screenshot from 2023-10-19 16-35-08](https://github.com/commons-app/apps-android-commons/assets/99590/7b2cf6d5-e03e-4b36-99b3-1af26b073a1c)

**Comment by nicolas-raoul** [comment]
@sivaraam Srishti fixed the unit tests, I replaced the Mapbox key, we can now consider that there are no blockers. :-) How about releasing a new beta, then upgrade to production [for 10% of the users](https://support.google.com/googleplay/android-developer/answer/6346149) in 24 hours?

**Comment by sivaraam** [comment]
[Tagged v4.2.1](https://github.com/commons-app/apps-android-commons/releases/tag/v4.2.1) and pushed the same for testing 👍🏼

**Comment by nicolas-raoul** [comment]
Only 2 ANR (Application Not Responding) and 1 crash so far, for all 4.2.x beta versions, each affecting 1 user:
<img width="790" alt="Screenshot 2023-10-27 at 15 07 02" src="https://github.com/commons-app/apps-android-commons/assets/99590/a4676f09-4124-467b-bccb-2c69ac3ab63f">

All of these 3 seem to have also happened recently in the production version, so they are not new bugs:
<img width="1325" alt="Screenshot 2023-10-27 at 15 15 28" src="https://github.com/commons-app/apps-android-commons/assets/99590/b6cca7de-1623-4aeb-9c2b-cb580e5b7710">

It looks pretty good to me. How about releasing now? :-)

**Comment by sivaraam** [comment]
Makes sense, Nicolas. I've sent the release for review 👍🏼

**Comment by sivaraam** [comment]
> Makes sense, Nicolas. I've sent the release for review 👍🏼

Just wanted to update that the release has been published successfully. So, closing this one :-)

**Comment by nicolas-raoul** [comment]
Wonderful, thanks all and especially @RitikaPahwa4444 thanks to whom this version is so reliable!
