### ISSUE TITLE
Urgent issues that should ideally be fixed before final publicity step

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#693]
As requested by @neslihanturan . :) I get that we can use labels, but the list itself is up for discussion, so instead of discussing it on the individual issues, we can discuss the general plans here.

My intended date to start the final publicity step (PR releases to general media, as I have already written for the Wikimedia blog and approached blogs that have written about us before) is 5 June 2017 or thereabouts. So the list needs to be attainable within a short period of time, no big suggestions please unless you think you may be able to pick the task up yourself. :)

My suggested tasks:

- [x] Make sure that #668 has been fixed in the recent patch
- [x] #650 
- [ ] #674 
- [x] Either revert to targeting API 23 or fix #457  
- [x] #686 (fixed, the further enhancement is not urgent)
- [x] #671 (if possible)

**Comment by misaochan** [comment]
I've just pushed v2.4.2 to beta, should be available in a few hours. We've managed to fix everything on that list except for #674 , but we can live with that. :)

Please help test 2.4.2 if at all possible. If all goes well, I'll push that to production in a few days' time, then finally everyone can get the new features that we worked on during the hackathon.
