### ISSUE TITLE
IEG renewal: Remaining steps

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#696]
For anyone who is interested in our IEG, I am listing the steps that need to be done before the previous IEG is considered complete, and the steps needed for renewal. At this stage, I think the chances of the grant being renewed will likely depend on endorsements (as well as how the committee judges my proposal). If anyone has any suggestions, feedback, etc, please do let me know.

Remaining steps for wrapping up IEG:

- [x] Solve urgent issues #693 
- [x] Create Youtube video #331 (whoops, almost forgot about this)
- [x] Final publicity step #420 
- [x] Collect measures of success metrics
- [x] Write final report based on those metrics
- [x] Have the IEG committee accept and sign off on the final report

Steps for renewing IEG:

- [x] Talk to Marti from the IEG committee (have not had a response from her)
- [x] Draft renewal proposal (including anyone who is interested in being part of the grant team)
- [x] Submit renewal proposal - https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal
- [x] Community announcements and endorsements
- [x] IEG committee makes decision

**Comment by misaochan** [comment]
Working my way through the final report currently. It seems that besides our individual metrics of success, we also need to report on global metrics. (For better formatting, see https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App/Final )

> 
> **Global Metrics[edit]**
> We are trying to understand the overall outcomes of the work being funded across all grantees. In addition to the measures of success for your specific program (in above section), please use the table below to let us know how your project contributed to the "Global Metrics." We know that not all projects will have results for each type of metric, so feel free to put "0" as often as necessary.
> 
> Next to each metric, list the actual numerical outcome achieved through this project.
> Where necessary, explain the context behind your outcome. For example, if you were funded for a research project which resulted in 0 new images, your explanation might be "This project focused solely on participation and articles written/improved, the goal was not to collect images."
> For more information and a sample, see Global Metrics.
> 
> Metric	Achieved outcome	Explanation
> 1. Number of active editors involved		
> 2. Number of new editors		
> 3. Number of individuals involved		
> 4. Number of new images/media added to Wikimedia articles/pages		
> 5. Number of articles added or improved on Wikimedia projects		
> 6. Absolute value of bytes added to or deleted from Wikimedia projects		

So the way I'm looking at it,
(1) is the number of people who have contributed pictures via our app? Difficult to measure exactly, no?
(2) is the number of new users who have contributed pictures via our app?
(3) Uh, would that be the people in (1) + technical contributors?
(4) I plan on using [this](https://tools.wmflabs.org/glamtools/glamorous.php?doit=1&category=Uploaded+with+Mobile%2FAndroid&use_globalusage=1&projects%5Bwikipedia%5D=1&projects%5Bwikimedia%5D=1&projects%5Bwikisource%5D=1&projects%5Bwikibooks%5D=1&projects%5Bwikiquote%5D=1&projects%5Bwiktionary%5D=1&projects%5Bwikinews%5D=1&projects%5Bwikivoyage%5D=1&projects%5Bwikispecies%5D=1&projects%5Bmediawiki%5D=1&projects%5Bwikidata%5D=1&projects%5Bwikiversity%5D=1) for the numbers
(5) Not sure how this differs from (4)
(6) ???

**Comment by misaochan** [comment]
Anyone have any ideas re: the global metrics? I still have no clue how we can measure any of that (except for 4). @whym @nicolas-raoul @VojtechDostal

**Comment by VojtechDostal** [comment]
Hello @misaochan, happy to help

(1) Number of active editors involved is number of "currently" active editors involved. Because this is a long-term project and also because measurement of active editors is used in Wikipedia, rarely in Wikimedia Commons, I would argue this is not applicable. 

(2) Number of new editors - basically people who didn't contribute to Wikimedia projects before they uploaded their pictures via the app. This is easy to measure via Wikimetrics if you have a list of uploaders (which we can obtain from the category: http://tools.wmflabs.org/ptools/uploadersincat.php?category=Uploaded+with+Mobile%2FAndroid). However you are probably interested in users who uploaded pictures after this project started. In that case you might use @whym 's Quarry tool but make sure it only captures the time range you are interested in. 

(3) Number of individuals involved - basically everyone who uploaded with the app in the given time frame, or helped with the app (eg.on GitHub) or developed it. You are sure to forget about someone, so just make a quick list. 

(4) Number of new images/media added to Wikimedia articles/pages - easy with the GLAMorous tool but are you sure you want to capture the full time frame of the category? 

(5) Number of articles added or improved on Wikimedia projects - does not apply to our project. Don't be afraid of omitting it - the grants team policy is that if metrics are not applicable, you don't have to report on them

(6) Absolute value of bytes added to or deleted from Wikimedia projects - again, only applicable to Wikipedia-based projects. Measuring megabytes of pictures in the upload category makes no sense at all.

**Comment by nicolas-raoul** [comment]
@VojtechDostal: What would be the GLAMorous tool request to get the number of media added to article **for all users of the app**? Thanks! :-)

**Comment by misaochan** [comment]
Thanks so much @VojtechDostal ! I will omit the suggested metrics. :)

(2) @whym 's tool automatically only starts counting from Jul 2016. However the main issue is that, AFAIK, it doesn't discern between iOS and Android uploads. This is likely not going to change the outcome much since the iOS app was pulled from the store before the grant even started, but it probably still has to be added as a disclaimer. I wonder if there is a way to get data solely from the Android app? I know "Uploaded with Mobile/Android" can be used as a tag in Commons but not sure how to get it to work with the Quarry tool.

(3) The uploadersincat tool you linked gives a good number for this, but is there a way to use that tool to filter for only uploaders who uploaded something from Jul 2016 - Jun 2017? I can get the number of GitHub contributors easily, but not sure how to get the number of uploaders within a certain timeframe 

(4) Yeah, I was wondering about this. The problem is that, unless I'm mistaken, GLAMorous doesn't seem to offer an option to select the timeframe.

**Comment by VojtechDostal** [comment]
What we need is to have a subcategory with images uploaded Jul 2016 - Jun 2017. We can then use this category to get the number of uploaders via Uploaders in Cat and number of usages via GLAMorous. That shouldn't be that difficult but Petscan times out when I try to get a list of images uploaded into that category during the above-mentioned period of time (60000 images is too much for Petscan). Maybe @whym could run a Quarry to get a list of these images? I can then ask someone to categorize them.

**Comment by whym** [comment]
For the number of images uploaded added to articles in a timeframe, using [Didym's gallery pages](https://commons.wikimedia.org/wiki/Special:PrefixIndex/User:Didym/Mobile_upload) seems to work. It looks like GLAMolous can handle a hundred of page titles: [link](https://tools.wmflabs.org/glamtools/glamorous.php?doit=1&category=&use_globalusage=1&ns0=1&gallerypages=User%3ADidym%2FMobile+upload%2F2016+April+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2016+April+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2016+April+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2016+April+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2016+April+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2016+April+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+August+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+December+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+10-14%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+15-19%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+20-24%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+25-29%0D%0AUser%3ADidym%2FMobile+upload%2F2016+February+5-9%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+January+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+July+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2016+June+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+March+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+May+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2016+November+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2016+October+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2016+September+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2017+April+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+14-18%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+19-23%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+24-28%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2017+February+9-13%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2017+January+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+1-5%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+11-15%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+16-20%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+21-25%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+26-30%0D%0AUser%3ADidym%2FMobile+upload%2F2017+June+6-10%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2017+March+9-12%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+1-4%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+13-16%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+17-21%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+22-26%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+27-31%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+5-8%0D%0AUser%3ADidym%2FMobile+upload%2F2017+May+9-12&projects[wikipedia]=1&projects[wikimedia]=1&projects[wikisource]=1&projects[wikibooks]=1&projects[wikiquote]=1&projects[wiktionary]=1&projects[wikinews]=1&projects[wikivoyage]=1&projects[wikispecies]=1&projects[mediawiki]=1&projects[wikidata]=1&projects[wikiversity]=1)

This again may contain iOS uploads in addition to Android, although I believe a vast majority is from Android. Perhaps you can randomly sample to estimate the ratio.

**Comment by misaochan** [comment]
@whym , the GLAMorous link you posted auto-times out for me.

Good idea re: the random sampling for iOS vs Android, I'll do that.

**Comment by misaochan** [comment]
Also, is there a way to automatically get a sum of the items in Didym's gallery pages?

**Comment by VojtechDostal** [comment]
I asked Martin Urbanec from our chapter to kindly help with the subcategory. It seems he could easily use Didym's gallery pages for that :-)

**Comment by VojtechDostal** [comment]
See https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android_(Jul_2016_-_Jun_2017)

**Comment by misaochan** [comment]
@VojtechDostal thanks for the link, but I wonder why there are only 208 files in that category? There should be a lot more than that from the looks of things.

**Comment by VojtechDostal** [comment]
It takes some time to fill that category and also Martin decided to ask for a bot flag because it seems someone didn't like using a bot without a flag. If you know someone who operates a bot... eg. @whym ? Then the list of files to be categorized is here: https://quarry.wmflabs.org/query/19871

**Comment by misaochan** [comment]
Oh, cool, thanks for the clarification. :) No worries, I'm heading off to bed soon anyway so I'll check on the category again tomorrow.

**Comment by misaochan** [comment]
(Also, please pass my thanks on to Martin :) )

**Comment by misaochan** [comment]
@VojtechDostal , do you think the category has been filled? The number (4589) is still different from the numbers in the [stats tool](https://github.com/whym/commons-app-stats/issues/1), which adds up to 20554.

**Comment by urbanecm** [comment]
You are right, my mistake. I'm going to fix it now. Sorry! --Martin U.

**Comment by misaochan** [comment]
Thanks so much @urbanecm ! :) When do you think I should check the category again?

**Comment by urbanecm** [comment]
It depends... I'm ending with around 50k (and not your 20k) of images and I'm wondering if this is correct. I've used this query https://quarry.wmflabs.org/query/19912.

**Comment by misaochan** [comment]
Wow, interesting lol. Any idea why the discrepancy with your stats tool, @whym ?

**Comment by misaochan** [comment]
One more thing - does the query check for new files or just for any edits made within the timespan? The app does a lot of edits (category additions) that aren't supposed to be counted.

**Comment by urbanecm** [comment]
I'm wondering why it tooked https://commons.wikimedia.org/w/index.php?title=File:Plant%C3%A0_Regne_2013_(4).jpeg&action=history when it has NO 2016 in its history. I probably misunderstood the aim of the cl_timestamp field. 

I'm going to make a new query which would look for upload-type logs in https://commons.wikimedia.org/wiki/Special:Log and would print images were uploaded within the timespan and are in Category:Uploaded_with_Mobile/Android.

**Comment by whym** [comment]
> the GLAMorous link you posted auto-times out for me.

Can you try pasting the titles of the gallery pages? https://commons.wikimedia.org/wiki/Special:PrefixIndex/User:Didym/Mobile_upload You will need to add the "User:" prefix.

https://tools.wmflabs.org/commons-app-stats/latest.csv.gz contains individual file titles with upload dates. Is this what you are looking for?

**Comment by urbanecm** [comment]
Yeah, it is but I need older data too. But it seems I've got it, around 20k of images, see https://quarry.wmflabs.org/query/19914. It looks okay. What do you think?

**Comment by urbanecm** [comment]
@misaochan Do you think https://quarry.wmflabs.org/query/19914 looks okay (I mean the results)? I don't want to do similar mistake again :-).

**Comment by misaochan** [comment]
@urbanecm Yes the last Quarry looks perfect to me, thanks! (Sorry, was away for a while)

**Comment by urbanecm** [comment]
Great @misaochan. Per IRC discussion with one of Commons's bureaucrats he prefer I fill the category with a flag so I'll wait for evaluation of my bot rights request (https://commons.wikimedia.org/wiki/Commons:Bots/Requests/UrbanecmBot).

**Comment by misaochan** [comment]
Oh okay, no worries @urbanecm . Do you think you could ping me when the category is ready to be used? Thanks so much again. :)

**Comment by misaochan** [comment]
@whym Sorry for the lack of clarification - Martin's sub-category is all that is currently needed, as when we have filled the category with images from the appropriate timespan, I can just paste it into UploadersInCat and GLAMorous. I was just wondering why his query was getting a widely divergent number from your stats tool, but that has been resolved now. Sorry about that!

**Comment by urbanecm** [comment]
Yeah, I'll ping you.

**Comment by urbanecm** [comment]
@misaochan I've got the flag so the category is being filled with the rest of results (some were in both of queries), currently around 6 edits/min, so around 2 days till the task would be completed.

**Comment by misaochan** [comment]
Thanks for the update @urbanecm ! 

@VojtechDostal I've been looking at the other grants that were renewed, and it seems like in some cases they started writing the renewal before the final report was signed off on (in one of their cases the final report was never even signed off on, but the renewal was approved!). 

In that case I think perhaps I could just start writing the renewal anyway, and I'll finalize the final report on Monday after the bot finishes?

**Comment by VojtechDostal** [comment]
Sounds good :-)

**Comment by misaochan** [comment]
Thanks for the new category, it works perfectly with Uploaders in cat and GLAMorous! :)

I'm wondering why the results at https://quarry.wmflabs.org/query/18084 have changed so much though, a week ago it was only 564. Did a whole bunch of people sign up? But the latest new user upload is tagged 20170627075711, not too recent.

**Comment by whym** [comment]
> I'm wondering why the results at https://quarry.wmflabs.org/query/18084 have changed so much though, a week ago it was only 564.

The query page is manually (but not automatically) updatable and I did it last week. The previous update was in April or earlier if I recall it correctly.

**Comment by misaochan** [comment]
Oh, okay, thanks! So the current results are more accurate, thus I can switch to using them?

**Comment by whym** [comment]
Yes, but note that I might re-run and update it again in future. It might be a good idea to save it somewhere as evidence. (You could even save the table into a subpage of the wiki page of your report - check the "Download data" menu.)

**Comment by misaochan** [comment]
The final report is now complete (whew!). :) Will be posting a draft of the renewal proposal shortly.

**Comment by misaochan** [comment]
The first draft of the renewal proposal is complete :) :
https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal

I'll be doing community notifications shortly, current plans are to post on:
- Mailing lists - wikitech-l, mobile-l, wikivoyage-l, commons-l
- Google group forums 
- Commons Village Pump 

Any other suggestions? Or if there are closed groups that you belong to whom you think might be interested in the app, would anyone like to post on those? I can help write a summary/cliffs notes of the (rather long) proposal for you to post if anyone needs one. 

Thanks!

**Comment by VojtechDostal** [comment]
I'll post it to CEE and Wikidata Facebook groups because people previously seemed interested in the app and wanted to support it.

**Comment by misaochan** [comment]
> I'll post it to CEE and Wikidata Facebook groups because people previously seemed interested in the app and wanted to support it.

Thanks, @VojtechDostal , that would be great! :) Shall I copy my mailing list post here when I've done them?

A somewhat silly question for anyone that might have an idea - what day of the week is best to post on mailing lists? A bit trivial, but I only get one shot at posting, haha (don't want to spam people), so might be good to make it count.

**Comment by misaochan** [comment]
Notifications done so far:

- [Commons Village Pump](https://commons.wikimedia.org/wiki/Commons:Village_pump#Commons_Android_app_-_IEG_renewal_proposal)
- [Wikivoyage Travellers' Pub](https://en.wikivoyage.org/wiki/Wikivoyage:Travellers%27_pub#Commons_Android_app_-_IEG_renewal_proposal)
- [Commons talk: Mobile app](https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app#IEG_renewal_proposal)

Will do the mailing lists shortly after.

**Comment by misaochan** [comment]
Posted to wikimedia-l, multimedia-l, wikitech-l, mobile-l, wikivoyage-l, commons-l. Got a mail delivery error from multimedia-l, maybe that mailing list doesn't exist anymore. 

If anyone knows anywhere else that I can post, please do let me know! A copy of my mailing list posts is below:

> Hi folks,
> 
> 
> The Wikimedia Commons app [1] (a community-maintained Android app that allows users to upload photos to Commons from their phone) was funded via an Individual Engagement Grant [2] last year and has several new features - a list and map of nearby places that need photos (based on Wikidata), category suggestions based on the image title, prevention of duplicate uploads, and a new tutorial to educate new users on what types of photos should or should not be uploaded. During the grant period, 20554 new files were uploaded via the app with an overall deletion rate of 15.74% (11.7% in the final two weeks after the new tutorial was implemented), and 3485 images that were uploaded via the app were used in Wikimedia articles. 
> 
> While we are very happy with the progress made, there are many other improvements that we would like to make but were not able to fit into the scope of the previous grant. Thus we are proposing a renewal [3] of the IEG in order to work on these. Highlights of the proposed improvements include:
> 
> - Enhancing the "Nearby places that need photos" feature by (1) allowing users to upload their image directly from a location on the list or map, with suggested title and categories based on the associated Wikidata item, and (2) displaying the user's real-time position on the map to allow easier navigation to the location they wish to photograph
> - Improving user education by displaying Commons account and user talk notifications (e.g. picture nominated for deletion) in the app, adding a gallery of featured images, and adding various notices and explanations in the upload screen
> - A sleeker, more intuitive, and more interactive user interface - a floating action button for uploads, "Nearby places that need photos" in a tab alongside the user's contributions, and a panel to display Commons account notifications and information about the nearest place that needs photos
> - Various technical and quality-of-life improvements, such as two-factor authentication login, multiple uploads, preventing overwrites, and fixing memory leaks and battery drain issues
> 
> We are especially excited about the "Nearby places that need photos" enhancements, as we feel that it can help reduce the number of geo-located Wikidata items that lack pictures, and provide pictures for Wikimedia articles that lack them. We believe that this is one of our main strengths as a mobile app - users can have a seamless workflow where they can browse the places that need photos, select one and move to the location, and then directly upload the photo after taking it (with relevant titles and categories suggested), all within the same app and without needing to use a computer.
> 
> Please do take a look at our proposal [3], feel free to provide feedback and make new suggestions on the Discussion page, and/or endorse the proposal if you see fit. If you would like to be part of the project, new volunteers and additions to our diverse team are always welcome - please visit our GitHub repository [4] and say "Hi". :)
> 
> Many thanks! 
> 
> 
> Regards,
> Josephine (Commons app project maintainer)
> 
> [1] https://play.google.com/store/apps/details?id=fr.free.nrw.commons
> [2] https://meta.wikimedia.org/wiki/Grants:IEG/Improve_%27Upload_to_Commons%27_Android_App
> [3] https://meta.wikimedia.org/wiki/Grants:Project/Improve_%27Upload_to_Commons%27_Android_App/Renewal
> [4] https://github.com/commons-app/apps-android-commons

**Comment by misaochan** [comment]
A brief update for those following the process: I have talked to Marti on 25 Aug, and was informed that we should have a decision on the renewal application in 2-3 weeks' time.
